function [baselineActivity, taskActivity] = calculatePhases(params,...
    alignment,alignWindow,siteSegs,siteTrialPSTHS,AUCCalc,keepTrials)
baselineWindow = [-5,-1];
baselineAlignPhases = ["GoSignal", "GoSignal"];
[baselineActivity, taskActivity] = deal(cell(1,length(siteTrialPSTHS)));
keyNames = params.condSegMap.keys;
taskInds = cellfun(@(tc,pc) cellfun(@(pa) arrayfun(@(s) find(strcmp(string(tc), s)),pa),pc,...
    'UniformOutput', false),params.condSegMap.values(keyNames(ismember(keys(params.condSegMap),keys(alignment)))),...
    values(alignment),'UniformOutput',false);
baselineInds = cellfun(@(cc) arrayfun(@(b) find(strcmp(string(cc),b)),...
    baselineAlignPhases,'UniformOutput', true),values(params.condSegMap,...
    params.condSegMap.keys()),'UniformOutput',false);
for c = 1:length(siteTrialPSTHS)
    if(~isempty(taskInds{c}))
        [baselineActivity{c}, taskActivity{c}] = calculateAUCBaselinePhases(params.bins,...
            taskInds{c},alignWindow{c},baselineInds{c},baselineWindow,siteSegs{c},...
            siteTrialPSTHS{c},AUCCalc,keepTrials);
    end
end
end

function [condBaseline, condPhases] = calculateAUCBaselinePhases(bins, ...
    phaseAlignment, phaseWindows,baselineAlignment,baselineWindow,alignTimes,psths,...
    AUCCalc,keepTrials)
binSize = mode(diff(bins));
%%% calculate AUC to determine task modulated units
% find start and end index in (1) each PSTH for (2) each phase
psthPhaseEnds = cellfun(@(a) cellfun(@(ps) cellfun(@(pa,pw) ...
    findBins(ps(:,pa)+pw,bins),phaseAlignment,phaseWindows,...
    'UniformOutput', false), a, 'UniformOutput', false),alignTimes,'UniformOutput', false);
% create mask that NaNs out all values outside of interrogated phase
% for each (1) PSTH for each (2) phase
psthPhaseMask = cellfun(@(ps) NaNMaskBins(ps,length(bins)),...
    psthPhaseEnds, 'UniformOutput', false);
psthBaselineMask = cellfun(@(pp) cellfun(@(p) max(ones(size(p,1),2),...
    findBins(p(:,baselineAlignment)+baselineWindow,bins)),...
    pp,'UniformOutput', false),alignTimes,'UniformOutput', false);

% bootstrapped sample of AUC in baseline window for each
% (1) PSTH for each (2) tested phase
% create equivalent sized start and end points in the baseline window
% for each (1) PSTH for each (2) phase AUC for each (1) PSTH for each tested phase
if(~keepTrials)
    psths = cellfun(@(c) cellfun(@(t) mean(t,3,'omitnan'), c, 'UniformOutput', false), psths, 'UniformOutput',false);
end
if(AUCCalc)
    condPhases = cellfun(@(udh,ud) cellfun(@(ps,u) cellfun(@(p)...
        (permute(trapz(u.*~isnan(permute(repmat(p,[1,1,size(u,1)]),[3 2 1])),2),[1 3 2])'./...
        sum(~isnan(p),2))',ps,'UniformOutput',false),udh,ud,'UniformOutput',false),psthPhaseMask,psths,'UniformOutput', false);
else
    condPhases = cellfun(@(udh,ud) cellfun(@(ps,u) cellfun(@(p)...
        permute(mean(u.*~isnan(permute(repmat(p,[1,1,size(u,1)]),[3 2 1])),...
        2,'omitnan'),[1 3 2]),ps,'UniformOutput',false),udh,{ud},'UniformOutput',false),psthPhaseMask,psths,'UniformOutput', false);
end
condBaseline = cellfun(@(p,ps,w) AUCBaselineBootstrap(p,{ps},w,binSize,AUCCalc,keepTrials) ,...
    psthBaselineMask,psths,psthPhaseEnds,'UniformOutput',false);
end


function nanMask = NaNMaskBins(ap,binLength)
nanMask = cellfun(@(pa) cellfun(@(s) NaN(size(s,1),binLength),...
    pa,'UniformOutput',false), ap,'UniformOutput', false);
for np = 1:length(ap)
    for p=1:length(ap{np})
        for n = 1:size(ap{np}{p},1)
            if(~any(isnan(ap{np}{p}(n,:))))
            nanMask{np}{p}(n,max(1,ap{np}{p}(n,1)) : ...
                min(binLength,ap{np}{p}(n,2))) = 1;
            end
        end
    end
end
end

function AUCPSTH = AUCBaselineBootstrap(ap,psths,winds,bSz,AUCCalc,trialMean)
NUMSBASELINESAMPLES = 10;
phaseL = cellfun(@(inWin) cell2mat(cellfun(@(w) w(:,2)-w(:,1), inWin,...
    'UniformOutput', false)), winds, 'UniformOutput', false)';
phaseL = num2cell(max(cat(3,phaseL{:}),[],3),1);
bBounds = cellfun(@(s) cellfun(@(e) [s(:,1),max(s(:,1),(s(:,2)-e))],...
    phaseL,'UniformOutput',false),ap, 'UniformOutput',false);
%bBounds = cellfun(@(a) cat(3,a{:}), bBounds, 'UniformOutput', false);
badTP = cellfun(@(tp) cellfun(@(t) any(isnan(t)|t<0,2),tp, 'UniformOutput',false),...
    bBounds,'UniformOutput', false);
medAUC = {};
for n = 1:NUMSBASELINESAMPLES
    smpMask = cellfun(@(n) repmat(1:size(n,2),size(n,3),1), psths,'UniformOutput',false);
    ss = cellfun(@(s) cellfun(@(ar) cellfun(@(t) randi(t,1), num2cell(ar,2),...
        'UniformOutput',true),s,'UniformOutput',false),bBounds,'UniformOutput', false);
    if(AUCCalc)
        nMed= cellfun(@(p,m,s,pb) cellfun(@(phs,phb,pl)(permute(trapz(p.*...
            permute(repmat((m<(pl+phs) & m>phs)&~phb,1,1,size(p,1)),[3 2 1]),2),...
            [1,3,2])'./pl)',s,pb,phaseL, 'UniformOutput', false),psths,smpMask,ss,badTP,...
            'UniformOutput', false)';
    else
        % nMed= cellfun(@(p,m,s,pb) cellfun(@(phs,phb,pl) permute(mean(p.*...
        %     permute(repmat((m<(pl+phs) & m>phs)&~phb,1,1,size(p,1)),[3 2 1])./...
        %     permute(repmat((m<(pl+phs) & m>phs)&~phb,1,1,size(p,1)),[3 2 1]),2,'omitnan'),...
        %     [1,3,2]),s,pb,phaseL, 'UniformOutput', false),psths,smpMask,ss,badTP,...
        %     'UniformOutput', false)';
        nMed= cellfun(@(p,m,s,pb) cellfun(@(phs,phb) permute(mean(p.*...
            permute(repmat((m<phs(:,2) & m>phs(:,1))&~phb,1,1,size(p,1)),[3 2 1])./...
            permute(repmat((m<phs(:,2) & m>phs(:,1))&~phb,1,1,size(p,1)),[3 2 1]),2,'omitnan'),...
            [1,3,2]),{s},{any(cell2mat(pb),2)}, 'UniformOutput', false),psths,smpMask,ap,badTP,...
            'UniformOutput', false)';
    end
    medAUC{n} = vertcat(nMed{:});
end
AUCPSTH = cellfun(@(m) {median(cat(3,m{:}),3,'omitnan')},num2cell([medAUC{:}],2),'UniformOutput',false)';
if(~trialMean)
    AUCPSTH = cellfun(@(a) {mean(a{:},2,'omitnan')}, AUCPSTH, 'UniformOutput', false);
end
end