function phaseAnalysis(repSave,sessionInds,phaseFR,taskFR,...
    baselineFR,masterPSTH,masterPhaseBins,taskUnitInds,unitPhaseInds,...
    condAbbrev,phaseNames,siteMasks,vXY,vMask,repColors,pVal,saveDirPath,saveName)
%%
for c = 1:length(taskUnitInds)-1
    tkInds = arrayfun(@(c) cast(c,'double'), taskUnitInds{c});
    tkInds(tkInds==0) = NaN;
    repSave(~taskUnitInds{c}) = {''};
    for p = 1:length(phaseNames)
        if(p==1)
            trialSIS = cellfun(@(rin, gin) cellfun(@(r,g) nanmean((r-g)./...
                (r+g)),rin,gin), phaseFR(c,3), phaseFR(c,4),'UniformOutput', false);
            rPU = cellfun(@(psth,r) trapz(binSize,psth(round(max(1,...
                nanmean(r(:,1)))):round(min(length(psth),nanmean(r(:,end))))))./...
                (diff(nanmean(r,1))),masterPSTH{c}, masterPhaseBins{c,3},'UniformOutput', true);
            gPU = cellfun(@(psth,g) trapz(binSize,psth(round(max(1,nanmean(g(:,1)))):...
                round(min(length(psth),nanmean(g(:,end))))))./(diff(nanmean(g,1))),...
                masterPSTH{c}, masterPhaseBins{c,4},'UniformOutput', true);
            unitSIS = arrayfun(@(r,g) (r-g)/(r+g), rPU, gPU, 'UniformOutput', true);
            
            trialSIS = trialSIS{1}.*tkInds;
            unitSIS = unitSIS.*tkInds;
            unitRGCount = (unitPhaseInds{c,3} - unitPhaseInds{c,4}).* tkInds;
            unitRCount = cellfun(@(r,g) ttest2(r(~isnan(r)),...
                g(~isnan(g)),'tail','right'), phaseFR{c,3}, phaseFR{c,4}, 'UniformOutput', false);
            unitGCount = cellfun(@(r,g) ttest2(g(~isnan(g)),...
                r(~isnan(r)),'tail','right'), phaseFR{c,3}, phaseFR{c,4}, 'UniformOutput', false);
            unitRCount(cellfun(@isempty, unitRCount)) = {NaN};
            unitRCount = cell2mat(unitRCount).*tkInds;
            unitGCount(cellfun(@isempty, unitGCount)) = {NaN};
            unitGCount = cell2mat(unitGCount).*tkInds;
            unitRGX = (unitRCount - unitGCount).* tkInds;
            
            trialFSI = modulatedUnitsPerRep(repSave,trialSIS,"SI",...
                string(sprintf('Reach \n - \n Grasp \n')),repColors);
            ylim([-.1 .1]);
            unitFSI = modulatedUnitsPerRep(repSave,unitSIS,"SI",...
                string(sprintf('Reach \n - \n Grasp \n')),repColors);
            ylim([-.1 .1]);
            saveFigures(trialFSI,[saveDirPath,'AUC\Trial\',condAbbrev{c},'\'],...
                [saveName,'_SI_Task_Trial'] ,[]);
            saveFigures(unitFSI,[saveDirPath,'AUC\Unit\',condAbbrev{c},'\'],...
                [saveName,'_SI_Task_Unit'] ,[]);
            unitRGFig = modulatedUnitsPerRep(repSave,int32(unitRGCount),...
                "Reach units - Grasp units","R-G",repColors);
            saveFigures(unitRGFig,[saveDirPath,'Count\',condAbbrev{c},'\'],...
                [saveName,'_R-G_units'],[]);
            unitRX = modulatedUnitsPerRep(repSave,int32(unitRCount),...
                "Rx units","Rx",repColors);
            saveFigures(unitRX,[saveDirPath,'Count\',condAbbrev{c},'\'],...
                [saveName,'_RX_units'],[]);
            unitGX = modulatedUnitsPerRep(repSave,int32(unitGCount),...
                "Gx units","Gx",repColors);
            saveFigures(unitGX,[saveDirPath,'Count\',condAbbrev{c},'\'],...
                [saveName,'_GX_units'],[]);
            unitRGXFig = modulatedUnitsPerRep(repSave,int32(unitRGX),...
                "Rx units - Gx units","Rx-Gx",repColors);
            saveFigures(unitRGXFig,[saveDirPath,'Count\',condAbbrev{c},'\'],...
                [saveName,'_RGX_units'],[]);
            %
            figMapUnit = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                unitSIS,true,5,[-.15, .15]);
            figMapTrial = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                trialSIS,true,5,[-.15 .15]);
            saveFigures(figMapTrial,[saveDirPath,'Maps\AUC\Trial\',...
                condAbbrev{c},'\'],[saveName,'_SI_Task_Trial'] ,[]);
            saveFigures(figMapUnit,[saveDirPath,'Maps\AUC\Unit\',...
                condAbbrev{c},'\'],[saveName,'_SI_Task_Unit'] ,[]);
            figMapRG = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                int32(unitRGCount),true,5,[-5 5]);
            saveFigures(figMapRG,[saveDirPath,'Maps\Count\',condAbbrev{c},'\'],...
                [saveName,'_R-G_units'],[]);
            figMapR = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                int32(unitRCount),true,5,[1 10]);
            saveFigures(figMapR,[saveDirPath,'Maps\Count\',condAbbrev{c},'\'],...
                [saveName,'_Rx_units'],[]);
            figMapG = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                int32(unitGCount),true,5,[1 10]);
            saveFigures(figMapG,[saveDirPath,'Maps\Count\',condAbbrev{c},'\'],...
                [saveName,'_Gx_units'],[]);
            figMapRGx = mapUnitVals(vXY,vMask,siteMasks,sessionInds,int32(unitRGX),...
                true,5,[-5 5]);
            saveFigures(figMapRGx,[saveDirPath,'Maps\Count\',condAbbrev{c},'\'],...
                [saveName,'_RGx_units'],[]);
            
            %% calculate condition modulated units (main effect and bonforonni corrected
            % condition compairsons)
            spToPInds = cellfun(@(ain,bin,cin) anova1([[ain;...
                NaN(max([length(ain),length(bin),length(cin)])-length(ain),1)],...
                [bin;NaN(max([length(ain),length(bin),length(cin)])-length(bin),1)],...
                [cin;NaN(max([length(ain),length(bin),length(cin)])-length(cin),1)]],[],'off'),...
                taskFR{1},taskFR{2},taskFR{3})<0.05;
            bothSphereCondInds = (~(cellfun(@(t) all(isnan(t)), taskFR{1}) | ...
                cellfun(@(t) all(isnan(t)), taskFR{2})));
            bothSphereCondInds = bothSphereCondInds & cellfun(@(s,c) ...
                ~(all(s==0) & all(c==0)), taskFR{1}, taskFR{2});
            spInds = false(1,length(bothSphereCondInds));
            spInds(bothSphereCondInds) = cellfun(@(ain,bin)...
                ttest2(ain(~isnan(ain)),bin(~isnan(bin)), 'alpha', pVal/2),...
                taskFR{1}(bothSphereCondInds), taskFR{2}(bothSphereCondInds));
            unitCM = modulatedUnitsPerRep(repSave,int32(spToPInds),...
                "Condition modulated units","Main effect",repColors);
            saveFigures(unitCM,[saveDirPath,'Count\Cond\'],...
                [saveName,'_Cond_modulated_units'],[]);
            unitSP = modulatedUnitsPerRep(repSave,int32(spInds),...
                "Sphere modulated units","Spheres",repColors);
            saveFigures(unitSP,[saveDirPath,'Count\Cond\'],[saveName,...
                '_Sphere_modulated_units'],[]);
            figMapConds = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                int32(spToPInds),true,5,[1 12]);
            saveFigures(figMapConds,[saveDirPath,'Maps\Count\Cond\'],...
                [saveName,'_Cond_modulated_units'],[]);
            figMapSpheres = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
                int32(spInds),true,5,[1 12]);
            saveFigures(figMapSpheres,[saveDirPath,'Maps\Count\Cond\'],...
                [saveName,'_Sphere_modulated_units'],[]);
            
        end
        unitPhase = cellfun(@(p,b) nanmean(p) - nanmean(b), phaseFR{c,p},...
            baselineFR{c}, 'UniformOutput', true);
        trialPhase = cellfun(@(pt, bt) cellfun(@(p,b) nanmean(p-b),pt,bt),...
            phaseFR(c,p), baselineFR(c),'UniformOutput', false);
        trialPhase = trialPhase{1}.*tkInds;
        unitPhase = unitPhase.*tkInds;
        unitCount = unitPhaseInds{c,p}.*tkInds;
        %
        trialAUC = modulatedUnitsPerRep(repSave,trialPhase,string([phaseNames{p},...
            '_Task_Trial']),"AUC (baseline subtracted)",repColors);
        ylim([-.01 .15]);
        unitAUC = modulatedUnitsPerRep(repSave,unitPhase,string([phaseNames{p},...
            '_Task_Unit']),"AUC (baseline subtracted)",repColors);
        ylim([-.01 .15]);
        saveFigures(trialAUC,[saveDirPath,'AUC\Trial\',condAbbrev{c},'\'],...
            [saveName,'_', phaseNames{p},'_Task_Trial'] ,[]);
        saveFigures(unitAUC,[saveDirPath,'AUC\Unit\',condAbbrev{c},'\'],...
            [saveName,'_', phaseNames{p},'_Task_Unit'] ,[]);
        unitCountFig = modulatedUnitsPerRep(repSave,int32(unitCount),...
            string([phaseNames{p}, ' units']), string(condAbbrev{c}),repColors);
        saveFigures(unitCountFig,[saveDirPath,'Count\', condAbbrev{c},'\'],...
            [saveName,'_',phaseNames{p},'_TaskUnits'],[]);
        
        figUnitPhase = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
            int32(unitPhase),true,5,[0, 25]);
        figTrialPhase = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
            int32(trialPhase),true,5,[0,25]);
        figUnitCount = mapUnitVals(vXY,vMask,siteMasks,sessionInds,...
            int32(unitCount),true,5,[0 25]);
        saveFigures(figTrialPhase,[saveDirPath,'Maps\AUC\Trial\',condAbbrev{c}],...
            [saveName,'_', phaseNames{p},'_Task_Trial'] ,[]);
        saveFigures(figUnitPhase,[saveDirPath,'Maps\AUC\Unit\',condAbbrev{c}],...
            [saveName,'_',phaseNames{p} '_Task_Unit'] ,[]);
        saveFigures(figUnitCount,[saveDirPath,'Maps\Count\',condAbbrev{c},'\'],...
            [saveName,'_',phaseNames{p} '_TaskUnits'] ,[]);
    end
end
end