ds = string();
monkey = 'Gilligan';
allS = dir(['S:\Lab\', monkey, '\All Data\']);
modelNames = {'Deltoid','Biceps', 'Triceps', 'Wrist Extensor', 'Wrist Flexor',...
    'Digit Extensor','Digit Flexor'};

events = containers.Map({'Extra Small Sphere', 'Large Sphere', 'Photocell', 'Rest'}, ...
    {{'GoSignal','StartReach','StartGrasp','StartLift','StartHold',...
    'StartWithdraw','StartReplaceHold','StartReplaceSuccess','StartReward'},...
    {'GoSignal','StartReach','StartGrasp','StartLift','StartHold',...
    'StartWithdraw','StartReplaceHold','StartReplaceSuccess','StartReward'},...
    {'GoSignal','StartReach','StartGrasp','StartHold',...
    'StartWithdraw','StartReplaceHold','StartReplaceSuccess','StartReward'},...
    {'GoSignal','StartReplaceHold', 'StartReplaceSuccess','StartReward'}});
conds = events.keys();

for m = 1:length(modelNames)
    for c = 1:length(conds)
        l = load(['S:\Lab\', monkey,'\Sorted EMG Data\Averages_Raw\',modelNames{m},'_',conds{c},'.mat']);
        rts = l.rawTrialsCond;      
    end
end